name: C/C++ CI

on: [push]

jobs:
  build:
    name: Test on ${{ matrix.build_tool }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        build_tool: [make, ninja]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: apt-get install cmake ninja-build
    - name: configure for ninja
      if: matrix.build_tool == 'ninja'
      run: mkdir build && cd build && cmake -GNinja ..
    - name: configure for make
      if: matrix.build_tool == 'make'
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cd build && cmake --build .
      
